# version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=trello-like
      - POSTGRES_USER=oscar
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-e2e:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_e2e
      - POSTGRES_USER=e2e
      - POSTGRES_PASSWORD=e2e123
    ports:
      - 5434:5432

  redis:
    image: redis:8
    ports:
      - 6379:6379

  redis-e2e:
    image: redis:8
    ports:
      - 6380:6379

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
